config/routes.rb
Rails.application.routes.draw do

  resources :boards do
    resources :lists, only: [:new, :create, :show, :edit, :update, :destroy]
  end

  resources :lists, only: [] do
    resources :tasks, only: [:new, :show, :create, :edit, :update, :destroy]
    resources :archive_tasks, only: [:update]
  end

  resources :registrations, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  root 'boards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'
  has_many :lists, dependent: :destroy
  validates :title, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
  has_many :tasks, dependent: :destroy
	validates :title, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :boards, foreign_key: 'owner_id'

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  validates :password_confirmation, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :warning, :danger, :info
  def current_user
    return @current_user if defined?(@current_user)
    @current_user = User.find_by(id: session[:current_user_id])
  end
  helper_method :current_user

end

app/controllers/archive_tasks_controller.rb
class ArchiveTasksController < ApplicationController
  def update
    list = List.find(params[:list_id])
    task = list.tasks.find(params[:id])
    task.update(archived: !task.archived)
    redirect_to board_list_path(list.board, list)
  end
end

# redirect ma dzialac, mozliwosc zmiany na archived bedac na widoku nie archived
# to samo na archived, notyfikacje

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all
  end

  def new
    @board = Board.new
  end

  def create
    @board = current_user.boards.new(board_params)
    if @board.save
      redirect_to board_path(@board), success: "Board created"
    else
      render :new
    end
  end

  def show
    board
  end

  def edit
    board
  end

  def update
    if board.update(board_params)
      redirect_to board_path(board), info: "Board updated"
    else
      render :edit
    end
  end

  def destroy
    board.destroy
    redirect_to root_path, danger: "Board deleted"
  end

  private

  def board_params
    params.require(:board).permit(:title)
  end

  def board
   @board ||= Board.find(params[:id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = board.lists.new
  end

  def show
    @archived =  params[:archived].present?
    @tasks = list.tasks.where(archived: @archived)
  end

  def create
    @list = board.lists.new(list_params)
    if @list.save
      redirect_to board_list_path(board, @list), success: "List created"
    else
      render :new
    end
  end

  def edit
    list
  end

  def update
    if list.update(list_params)
    redirect_to board_path(board, list), info: "List updated"

    else
      render :edit
    end
  end

  def destroy
    list.destroy
    redirect_to boards_path, danger: "List deleted"
  end

  private

  def list_params
    params.require(:list).permit(:title)
  end

  def board
    @board ||= Board.find(params[:board_id])
  end

  def list
    @list ||= board.lists.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path, success: "Successfully signed up please log in!"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to root_path, success: "Logged in!"
    else
      flash.now[:danger] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:current_user_id] = nil
    flash[:success] = "Logged out!"
    redirect_to root_url
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = list.tasks.new
  end

  def create
    @task = list.tasks.new(task_params)
    if @task.save
      redirect_to board_list_path(list.board, list), success: "Task created"
    else
      render :new
    end
  end 

  def edit
    task
  end

  def update
    if task.update(task_params)
      redirect_to board_list_path(list.board, list), info: "Task updated"
    else
      render :new
    end
  end

  private

  def task_params
    params.require(:task).permit(:title)
  end

  def list
    @list ||= List.find(params[:list_id])
  end

  def task
    @task ||= list.tasks.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @board do |f| %>
      <%= render 'shared/errors', obj: @board %>
      <%= f.text_field :title, class: 'form-control' %>
      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/boards/edit.html.erb
<h1>New board</h1>

<%= render 'form' %> 

app/views/boards/index.html.erb
<% if current_user %>

<h1>Your boards</h1>
<%= link_to "New board", new_board_path, class: 'btn btn-primary' %>

<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @boards.each do |board| %>
    <% if board.owner == current_user %>
      <tr>
        <td><%= board.id %></td>
        <td><%= board.title %></td>
        <td><%= link_to "Show", board_path(board), class: 'btn btn-sm btn-default' %></td>
        <td><%= link_to "Edit", edit_board_path(board), class: 'btn btn-sm btn-info' %></td>
        <td><%= link_to "Delete", board_path(board), class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
      <% end  %>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/boards/new.html.erb
<h1>New board</h1>

<%= render 'form' %>

app/views/boards/show.html.erb
<h1>Board: <%= @board.title %></h1>

<%= link_to "Add new list", new_board_list_path(@board), class: 'btn btn-primary' %>

<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @board.lists.each do |list| %>
      <% if list.board.owner == current_user %>
      <tr>
        <td><%= list.id %></td>
        <td><%= list.title %></td>
        <td><%= link_to "Show", board_list_path(@board, list), class: 'btn btn-sm btn-default' %></td>
        <td><%= link_to "Edit", edit_board_list_path(@board, list), class: 'btn btn-sm btn-info' %></td>
        <td><%= link_to "Delete", board_list_path(@board, list), class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to "Back", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apka</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: './shared/header' %>
    <div class="container">
    <%= render partial: './shared/alerts' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [@board, @list] do |f| %>
      <%= render 'shared/errors', obj: @list %>
      <%= f.text_field :title, class: 'form-control' %>
      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/lists/edit.html.erb
<h1>Edit list</h1>

<%= render 'form' %> 

app/views/lists/new.html.erb
<%= form_for [@board, @list] do |f| %>
	<% if @list.errors.present? %>
		<ul>
			<% @list.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>
	<%= f.text_field :title %>
	<%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1>List: <%= @list.title %></h1>

<%= link_to "Add new task", new_list_task_path(@list), class: 'btn btn-sm btn-primary' %>
<% if @archived.present? %> 
  <%= link_to "Back to tasks", board_list_path(@board, @list) %>
<% else %>
  <%= link_to "Archived tasks", board_list_path(@board, @list, archived: true) %>
<% end %>
<table class="table">
  <thead>
    <tr>
      <th>ToDo</th>
      <th colspan="2">Actions</th>
    </tr>  
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= link_to "Edit", edit_list_task_path(@list, task), class: 'btn btn-xs btn-info' %></td>
        <td><%= link_to "Add to archive", list_archive_task_path(@list, task), class: 'btn btn-xs btn-info', method: :put %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Back", board_path(@board) %>

app/views/shared/_alerts.html.erb
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form contains <%= pluralize(obj.errors.count, "error") %>.
  </div>
  <ul>
    <%- obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "APKA", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><%= link_to 'Signout', session_path(current_user), method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign up", new_registration_path %></li> | 
        <li><%= link_to "Sign in", new_session_path %></li>
      <% end %>
      </ul>
    </nav> 
  </div>
</header>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [@list, @task] do |f| %>
      <%= render 'shared/errors', obj: @task %>
      <%= f.text_field :title, class: 'form-control' %>
      <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= render 'form' %> 

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>